
name: 1. Simple AWS Deploy

# Controls when the workflow will run
on:
  push:
    branches: [ "dry-run" ]
  workflow_dispatch:
# OIDC Permission
permissions: 
  id-token: write
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region:  eu-central-1
          role-to-assume: ${{ variables.AWS_IAM_ROLE }}
          output-credentials: true

      - name: Verify assumed identity
        run: aws sts get-caller-identity
          
